spring.application.name=ticketing-system

# Aiven Cloud MySQL Connection
spring.datasource.url=jdbc:mysql://mysql-1cc0a93d-tarun.j.aivencloud.com:22400/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_Tw8sKfHXXiKGRlW1_QF

# Hibernate & Data Layer Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect